123
urfu-2017/webdev-task-5 pull request #11
Opened 2018-04-02 16:49 UTC by Morkhod

2018-04-02 16:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-04-02 16:51 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 10 из 10

2018-04-12 08:03 UTC, nex2hex commented on queries.js
> +            price: { type: Number, index: true },
поиск в методе осуществляется по трем полям, лучше их объединить в один индекс

2018-04-12 08:05 UTC, nex2hex requested changes
🍅

2018-04-12 08:05 UTC, nex2hex commented on queries.js
> +            const souvenir = await this._Souvenir.findOne({ _id: id });
а вот это не ок
у тебя в цикле запросы выполняются последовательно синхронно
это очень долго

сделай одним запросом

2018-04-12 18:22 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 10 из 10

2018-04-12 18:26 UTC, nex2hex commented
🍏

2018-04-12 18:26 UTC, closed without merging